name: daily_voca
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # 상태관리
  provider: ^6.1.1

  # 로컬 DB
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # UI/UX
  flutter_card_swiper: ^7.0.1
  fl_chart: ^0.66.0

  # 발음 듣기(TTS)
  flutter_tts: ^4.0.2

  # 유틸리티
  intl: ^0.19.0
  shared_preferences: ^2.2.2

  # HTTP 통신
  http: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
